#checking helmfile
helmfiles:
  # - path: ./charts/backbone-services/backboneservices-helmfile.yaml
  - path: ./charts/core-services/coreservices-helmfile.yaml
  # - path: ./charts/frontend/frotendservices-helmfile.yaml
  # - path: ./charts/urban/urbanservices-helmfile.yaml
  - path: ./charts/common-services/common-serviceservices-helmfile.yaml


